### ISSUE TITLE
Unable to yarn start or node dist/main

### ISSUE THREAD

**Issue by thachp-mhc** [adamjq/production-ready-serverless-nestjs#102]
I keep getting this error even after building.

Repros: 
```
- git clone git@github.com:adamjq/production-ready-serverless-nestjs.git
- yarn install
- yarn build
- yarn start
```

Output
```
yarn run v1.22.19
$ nest start
error TS8022: JSDoc '@extends' is not attached to a class.

Found 1 error(s).

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by adamjq** [comment]
Thanks @thachp-mhc 

I've tested this locally and it works with `yarn start:dev`. I'll look into that error

**Comment by adamjq** [comment]
Note that `yarn build` is for building with Webpack and isn't necessary to run the server locally

**Comment by thachp-mhc** [comment]
> Thanks @thachp-mhc
> 
> I've tested this locally and it works with `yarn start:dev`. I'll look into that error

confirmed.  `yarn start:dev` works for me too.  
I get the error when i ran `yarn start ` or `node dist/main.js`

**Comment by thachp-mhc** [comment]
I resolved the issue by deleting the entire /node_modules and reinstall it.  Thanks for looking into this.
